#!/usr/bin/env node
require("babel/register"); // don't put anything above this line!

// parse command line
var nopt = require("nopt")
  , Stream = require("stream").Stream
  , path = require("path")
    , knownOpts = { "phrase" : [String, null]
                , "mem" : Number
                , "time" : Number
                , "file" : [String, Array]
                , "storm" : Boolean
                }
  , shortHands = { "p" : ["--phrase"]
                 , "m" : ["--mem"]
                 , "t" : ["--time"]
                 , "f" : ["--file"]
                 , "s" : ["--storm"]
                 }
  , parsed = nopt(knownOpts, shortHands, process.argv, 2)

if(parsed.storm) {
	require("./storm.js")
	process.exit();
}


if(!parsed.file) {
  console.log('Specify file list with -f');
  process.exit();
}

var fs = require('fs')
var model = require('./src/model'),
  Board = model.Board,
  Unit = model.Unit,
  Game = model.Game;
var read = require('./src/reader');



var answer = [];
parsed.file.forEach(function(fileName, i, arr) {
	data = fs.readFileSync(fileName);  
  task = JSON.parse(data);


  var game = read(task);
  task.sourceSeeds.forEach(function(seed, i, arr) {

    var rand = game.board.getRandomGenerator(seed);
    var unitNum = rand()%task.units.length;  
    //console.log(unitNum);

    var unit = new Unit(task.units[unitNum].pivot, task.units[unitNum].members);
    //console.log(unit);
    game.unit = game.spawn(game.board, unit);
    //game.display();

  });

  // TODO: solve problem here

  var entry = {
      problemId : task.id,
      seed : task.sourceSeeds[0],
      tag : 'first',
      solution : 'amamamamam'
    };  
  answer.push(entry);
});

console.log(JSON.stringify(answer));